<?php
require_once __DIR__.'/../config/config.php'; admin_required();
$id=(int)($_GET['id']??0); $p=$id?db()->prepare("SELECT * FROM products WHERE id=?"):null; if($p){$p->execute([$id]);$p=$p->fetch();} else $p=[];
$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check($_POST['csrf']??null);$data=[trim($_POST['sku']),trim($_POST['name']),trim($_POST['category']),trim($_POST['description']),floatval($_POST['price']),floatval($_POST['cost']),intval($_POST['stock']),trim($_POST['sizes']),trim($_POST['colors']),$_POST['status'],isset($_POST['featured'])?1:0];
$image=$p['image']??''; if(!empty($_FILES['image']['name']) && is_uploaded_file($_FILES['image']['tmp_name'])){ $ext=strtolower(pathinfo($_FILES['image']['name'],PATHINFO_EXTENSION)); if(in_array($ext,['jpg','jpeg','png','webp'],true)){ $name=bin2hex(random_bytes(8)).'.'.$ext; move_uploaded_file($_FILES['image']['tmp_name'],__DIR__.'/../uploads/products/'.$name); $image='uploads/products/'.$name;}}
try{if($id){$st=db()->prepare("UPDATE products SET sku=?,name=?,category=?,description=?,price=?,cost=?,stock=?,sizes=?,colors=?,status=?,featured=?,image=? WHERE id=?");$st->execute([...$data,$image,$id]);}else{$st=db()->prepare("INSERT INTO products (sku,name,category,description,price,cost,stock,sizes,colors,status,featured,image) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");$st->execute([...$data,$image]);}redirect('products.php');}catch(Throwable $e){$err='Could not save product. SKU may already exist.';}}
$title=$id?'Edit product':'Add product';require __DIR__.'/admin_header.php'; ?>
<section class="admin-panel"><h1><?=$id?'Edit':'Add'?> product</h1><?php if($err):?><div class="alert"><?=e($err)?></div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="form-grid"><?php $vals=['sku'=>'SKU','name'=>'Name','category'=>'Category','price'=>'Selling price','cost'=>'Supplier cost','stock'=>'Stock','sizes'=>'Sizes (comma separated)','colors'=>'Colours (comma separated)'];foreach($vals as $k=>$label):?><label><?=e($label)?><input name="<?=$k?>" value="<?=e($p[$k]??'')?>" required></label><?php endforeach;?></div><label>Description<textarea name="description" rows="6"><?=e($p['description']??'')?></textarea></label><label>Status<select name="status"><?php foreach(['active','draft','archived'] as $s):?><option <?=$s===($p['status']??'active')?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label><input type="checkbox" name="featured" <?=!empty($p['featured'])?'checked':''?>> Featured</label><label>Product image<input type="file" name="image" accept="image/*"></label><button class="btn btn-dark">Save product</button></form></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
